apiVersion: apps/v1
kind: Deployment          # <--- Type de ressource : Un Déploiement
metadata:
  name: devops-project-deployment
spec:
  replicas: 1             # <--- On veut 1 seul clone de l'application
  selector:
    matchLabels:
      app: devops-project # <--- Ce déploiement gère les pods étiquetés "devops-project"
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project-container
        image: medkallel/devops-project:latest  # (votre nom d'image)
        imagePullPolicy: Always                 # <--- AJOUTEZ CETTE LIGNE ICI
        ports:
        - containerPort: 5000
        imagePullPolicy: Always # <--- Force à retélécharger l'image si elle change